### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by vergissberlin** [netresearch/ansible-role-raspberry-pi#1]
*Acceptance criterias:* 
https://drive.google.com/drive/folders/1O-fmiAw0iKByQ_Usv8mRW0oC8AW1WYaN

**Comment by Normo** [comment]
Hi @TheDevMinerTV

## code review
- Mail address typo - https://github.com/netresearch/ansible-role-raspberry-pi/blob/master/meta/main.yml#L3
- change company to Netresearch DTT GmbH - https://github.com/netresearch/ansible-role-raspberry-pi/blob/master/meta/main.yml#L5
- Debian Wheezy already reached EOL - https://github.com/netresearch/ansible-role-raspberry-pi/blob/master/meta/main.yml#L11
- update the apt cache before doing the upgrade instead afterwards - https://github.com/netresearch/ansible-role-raspberry-pi/blob/master/tasks/packages.yml#L20
- var 'packages.os' may conflict with same name variable from server-base role (maybe packages.pi would be better name) -
https://github.com/netresearch/ansible-role-raspberry-pi/blob/master/vars/main.yml#L3

- [README.md](https://github.com/netresearch/ansible-role-raspberry-pi/blob/master/README.md) could be more detailed
- I'm missing any tests :see_no_evil:

**Comment by TheDevMinerTV** [comment]
@Normo I still have 2 Pi's running Raspbian Wheezy. I don't want to upgrade.

**Comment by Normo** [comment]
Code review done
